version: '3.5'

services: 
    frontend:
        image: node-app
        ports:
            - 5000:5000
    
    backend:
        image: go-app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 8080:8080

    redis:
        image: redis        
        ports:
            - 6379:6379
