version: '3.5'

services:
    frontend:
        image: node-app-nginx
        ports:
            - 5000:5000        

    backend:
        image: go-app-nginx
        ports:
            - 8080:8080
        environment:            
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=example
            - POSTGRES_USER=postgres
            - POSTGRES_DATABASE=postgres
        depends_on:
            - redis
            - db            

    redis:
        image: redis
        ports:
            - 6379:6379

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=example
            - PGDATA=/database
        ports:
            - 5432:5432

    proxy:
        image: nginx:1.19-alpine
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        environment:
            - NGINX_PORT=80