version: '3.7'

services:
  simple-node-app:
    build: .
    command: npm start
    ports: 
      - 3001:3001
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: simple-node-app

volumes:
    node_modules: